# EVE Registers


REG_TRACKER                    = 0x7f004000   #   Tracker register 0
REG_TRACKER_1                  = 0x7f004004   #   Tracker register 1
REG_TRACKER_2                  = 0x7f004008   #   Tracker register 2
REG_TRACKER_3                  = 0x7f00400c   #   Tracker register 3
REG_TRACKER_4                  = 0x7f004010   #   Tracker register 4
REG_MEDIAFIFO_READ             = 0x7f004014   #   media FIFO read offset
REG_MEDIAFIFO_WRITE            = 0x7f004018   #   media FIFO write offset
REG_FLASH_SIZE                 = 0x7f004024   #   Detected flash capacity, in Mbytes
REG_ANIM_ACTIVE                = 0x7f00402c   #   32-bit mask of currently playing animations
REG_OBJECT_COMPLETE            = 0x7f004038   #   Used with OPT_COMPLETEREG
REG_EXTENT_X0                  = 0x7f00403c   #   Previous widget pixel extents
REG_EXTENT_Y0                  = 0x7f004040   #   Previous widget pixel extents
REG_EXTENT_X1                  = 0x7f004044   #   Previous widget pixel extents
REG_EXTENT_Y1                  = 0x7f004048   #   Previous widget pixel extents
REG_PLAY_CONTROL               = 0x7f004050   #   Video playback control
REG_ID                         = 0x7f006000   #   Identification register, always reads as 0x7c
REG_FRAMES                     = 0x7f006004   #   Frame counter, since reset
REG_CLOCK                      = 0x7f006008   #   Clock cycles, since reset
REG_FREQUENCY                  = 0x7f00600c   #   Main clock frequency
REG_RE_DEST                    = 0x7f006010   #   RE destination address
REG_RE_FORMAT                  = 0x7f006014   #   RE format, as bitmap format
REG_RE_ROTATE                  = 0x7f006018   #   RE rotate control
REG_RE_W                       = 0x7f00601c   #   RE target width, in pixels
REG_RE_H                       = 0x7f006020   #   RE target height, in pixels
REG_RE_DITHER                  = 0x7f006024   #   RE target dither enable
REG_RE_ACTIVE                  = 0x7f006028   #   RE write path active
REG_RE_RENDERS                 = 0x7f00602c   #   RE render counter
REG_SC0_RESET                  = 0x7f006034   #   Swapchain 0, write to reset
REG_SC0_SIZE                   = 0x7f006038   #   Swapchain 0, ring size 1-4
REG_SC0_PTR0                   = 0x7f00603c   #   Swapchain 0, pointer 0
REG_SC0_PTR1                   = 0x7f006040   #   Swapchain 0, pointer 1
REG_SC0_PTR2                   = 0x7f006044   #   Swapchain 0, pointer 2
REG_SC0_PTR3                   = 0x7f006048   #   Swapchain 0, pointer 3
REG_SC1_RESET                  = 0x7f00604c   #   Swapchain 0, write to reset
REG_SC1_SIZE                   = 0x7f006050   #   Swapchain 0, ring size 1-4
REG_SC1_PTR0                   = 0x7f006054   #   Swapchain 0, pointer 0
REG_SC1_PTR1                   = 0x7f006058   #   Swapchain 0, pointer 1
REG_SC1_PTR2                   = 0x7f00605c   #   Swapchain 0, pointer 2
REG_SC1_PTR3                   = 0x7f006060   #   Swapchain 0, pointer 3
REG_SC2_RESET                  = 0x7f006064   #   Swapchain 0, write to reset
REG_SC2_SIZE                   = 0x7f006068   #   Swapchain 0, ring size 1-4
REG_SC2_PTR0                   = 0x7f00606c   #   Swapchain 0, pointer 0
REG_SC2_PTR1                   = 0x7f006070   #   Swapchain 0, pointer 1
REG_SC2_PTR2                   = 0x7f006074   #   Swapchain 0, pointer 2
REG_SC2_PTR3                   = 0x7f006078   #   Swapchain 0, pointer 3
REG_CPURESET                   = 0x7f006088   #   Coprocessor reset bits 2:JA 1:JT 0:J1
REG_HCYCLE                     = 0x7f00608c   #   Horizontal total cycle count
REG_HOFFSET                    = 0x7f006090   #   Horizontal display start offset
REG_HSIZE                      = 0x7f006094   #   Horizontal display pixel count
REG_HSYNC0                     = 0x7f006098   #   Horizontal sync fall offset
REG_HSYNC1                     = 0x7f00609c   #   Horizontal sync rise offset
REG_VCYCLE                     = 0x7f0060a0   #   Vertical total cycle count
REG_VOFFSET                    = 0x7f0060a4   #   Vertical display start offset
REG_VSIZE                      = 0x7f0060a8   #   Vertical display line count
REG_VSYNC0                     = 0x7f0060ac   #   Vertical sync fall offset
REG_VSYNC1                     = 0x7f0060b0   #   Vertical sync rise offset
REG_DLSWAP                     = 0x7f0060b4   #   Display list swap control
REG_PCLK_POL                   = 0x7f0060b8   #   PCLK polarity, 0 = clock on rising, 1 = falling
REG_TAG_X                      = 0x7f0060bc   #   Tag query X coordinate
REG_TAG_Y                      = 0x7f0060c0   #   Tag query Y coordinate
REG_TAG                        = 0x7f0060c4   #   Tag query result
REG_VOL_L_PB                   = 0x7f0060c8   #   Volume for playback left
REG_VOL_R_PB                   = 0x7f0060cc   #   Volume for playback right
REG_VOL_SOUND                  = 0x7f0060d0   #   Volume for synth sound
REG_SOUND                      = 0x7f0060d4   #   Sound effect select
REG_PLAY                       = 0x7f0060d8   #   Start effect playback
REG_GPIO_DIR                   = 0x7f0060dc   #   GPIO pin direction, 1 = output
REG_GPIO                       = 0x7f0060e0   #   GPIO read/write
REG_DISP                       = 0x7f0060e4   #   DISP output
REG_INT_FLAGS                  = 0x7f006100   #   Interrupt flags
REG_INT_EN                     = 0x7f006104   #   Global interrupt enable
REG_INT_MASK                   = 0x7f006108   #   Interrupt enable mask
REG_PLAYBACK_START             = 0x7f00610c   #   Audio playback RAM start address
REG_PLAYBACK_LENGTH            = 0x7f006110   #   Audio playback sample length (bytes)
REG_PLAYBACK_READPTR           = 0x7f006114   #   Audio playback current read pointer
REG_PLAYBACK_FREQ              = 0x7f006118   #   Audio playback frequency (Hz)
REG_PLAYBACK_FORMAT            = 0x7f00611c   #   Audio playback format
REG_PLAYBACK_LOOP              = 0x7f006120   #   Audio playback loop enable
REG_PLAYBACK_PLAY              = 0x7f006124   #   Start audio playback
REG_PWM_HZ                     = 0x7f006128   #   PWM output frequency (Hz)
REG_PWM_DUTY                   = 0x7f00612c   #   PWM output duty cycle 0=0\%, 128=100\%
REG_MACRO_0                    = 0x7f006130   #   Display list macro command 0
REG_MACRO_1                    = 0x7f006134   #   Display list macro command 1
REG_CMD_READ                   = 0x7f00614c   #   Command buffer read pointer
REG_CMD_WRITE                  = 0x7f006150   #   Command buffer write pointer
REG_CMD_DL                     = 0x7f006154   #   Command DL offset
REG_CTOUCH_EXTENDED            = 0x7f00615c   #   0: single-touch, 1: multi-touch
REG_CTOUCH_TOUCH0_XY           = 0x7f006160   #   Touchscreen screen $(x,y)$ (16, 16)
REG_TOUCH_SCREEN_XY            = 0x7f006160   #   Touchscreen screen $(x,y)$ (16, 16)
REG_CTOUCH_TOUCHA_XY           = 0x7f006164   #   Touchscreen raw $(x,y)$ (16, 16)
REG_TOUCH_RAW_XY               = 0x7f006164   #   Touchscreen raw $(x,y)$ (16, 16)
REG_CTOUCH_TOUCHB_XY           = 0x7f006168   #   Touchscreen touch 2
REG_CTOUCH_TOUCHC_XY           = 0x7f00616c   #   Touchscreen touch 3
REG_CTOUCH_TOUCH4_XY           = 0x7f006170   #   Touchscreen touch 4
REG_TOUCH_TAG_XY               = 0x7f006174   #   Touchscreen screen $(x,y)$ used for tag lookup
REG_TOUCH_TAG                  = 0x7f006178   #   Touchscreen tag result 0
REG_TOUCH_TAG1_XY              = 0x7f00617c   #   Touchscreen screen $(x,y)$ used for tag lookup
REG_TOUCH_TAG1                 = 0x7f006180   #   Touchscreen tag result 1
REG_TOUCH_TAG2_XY              = 0x7f006184   #   Touchscreen screen $(x,y)$ used for tag lookup
REG_TOUCH_TAG2                 = 0x7f006188   #   Touchscreen tag result 2
REG_TOUCH_TAG3_XY              = 0x7f00618c   #   Touchscreen screen $(x,y)$ used for tag lookup
REG_TOUCH_TAG3                 = 0x7f006190   #   Touchscreen tag result 3
REG_TOUCH_TAG4_XY              = 0x7f006194   #   Touchscreen screen $(x,y)$ used for tag lookup
REG_TOUCH_TAG4                 = 0x7f006198   #   Touchscreen tag result 4
REG_TOUCH_TRANSFORM_A          = 0x7f00619c   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_TRANSFORM_B          = 0x7f0061a0   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_TRANSFORM_C          = 0x7f0061a4   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_TRANSFORM_D          = 0x7f0061a8   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_TRANSFORM_E          = 0x7f0061ac   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_TRANSFORM_F          = 0x7f0061b0   #   Touchscreen transform coefficient (s15.16)
REG_TOUCH_CONFIG               = 0x7f0061b4   #   Touchscreen configuration
REG_CMDB_SPACE                 = 0x7f006594   #   Command DL (bulk) space available
REG_PLAYBACK_PAUSE             = 0x7f0065d0   #   audio playback pause, 0=play 1=pause
REG_FLASH_STATUS               = 0x7f0065d4   #   Flash status 0=INIT 1=DETACHED 2=BASIC 3=FULL
REG_SO_MODE                    = 0x7f0065f4   #   Scanout pixel mode
REG_SO_SOURCE                  = 0x7f0065f8   #   Scanout 0 source
REG_SO_FORMAT                  = 0x7f0065fc   #   Scanout 0 format
REG_SO_EN                      = 0x7f006600   #   Scanout 0 enable
REG_I2S_EN                     = 0x7f006714   #   I2S interface enable
REG_I2S_FREQ                   = 0x7f006718   #   I2S sample frequency
REG_SC2_STATUS                 = 0x7f006780   #   Swapchain 2 status, write to reset
REG_SC2_ADDR                   = 0x7f006784   #   Swapchain 2 status, write to reset

# System Registers

REG_LVDSRX_CORE_ENABLE         = 0x7f006670   #   LVDSRX enable register
REG_LVDSRX_CORE_CAPTURE        = 0x7f006674   #   LVDSRX enable capture register
REG_LVDSRX_CORE_SETUP          = 0x7f006678   #   LVDSRX pixel setup control register
REG_LVDSRX_CORE_DEST           = 0x7f00667c   #   LVDSRX destination frame address register
REG_LVDSRX_CORE_FORMAT         = 0x7f006680   #   LVDSRX output pixel format register
REG_LVDSRX_CORE_DITHER         = 0x7f006684   #   LVDSRX enable dither register
REG_LVDSRX_CORE_FRAMES         = 0x7f006698   #   LVDSRX frame counter
REG_LVDSRX_SETUP               = 0x7F800500   #   LVDSRX system set-up
REG_LVDSRX_CTRL                = 0x7F800504   #   LVDSRX analog block configuration
REG_LVDSRX_STAT                = 0x7F800508   #   LVDSRX status register
REG_LVDSTX_EN                  = 0x7f800300   #   LVDS enables
REG_LVDSTX_PLLCFG              = 0x7f800304   #   LVDS PLL and Clock configuration
REG_LVDSTX_CTRL_CH0            = 0x7f800314   #   LVDS channel 0 control
REG_LVDSTX_CTRL_CH1            = 0x7f800318   #   LVDS channel 1 control
REG_LVDSTX_STAT                = 0x7f80031c   #   LVDS status
REG_LVDSTX_ERR_STAT            = 0x7f800320   #   LVDS error status

REG_PIN_DRV_0                  = 0x7f800408   #   Pin drive strength setting
REG_PIN_DRV_1                  = 0x7f80040C   #   Pin drive strength setting
REG_PIN_SLEW_0                 = 0x7f800410   #   Pin output slew rate setting
REG_PIN_TYPE_0                 = 0x7f800414   #   Pin type setting
REG_PIN_TYPE_1                 = 0x7f800418   #   Pin type setting
REG_SYS_CFG                    = 0x7f800420   #   Miscellaneous system configuration
REG_SYS_STAT                   = 0x7f800424   #   System status
REG_CHIP_ID                    = 0x7f800448   #   CHIP_ID info
REG_BOOT_STATUS                = 0x7f80044C   #   EVE boot status
REG_DDR_TYPE                   = 0x7f800454   #   DDR DRAM type setting
REG_PIN_DRV_2                  = 0x7f800464   #   Pin drive strength setting
REG_PIN_SLEW_1                 = 0x7f800468   #   Pin output slew rate setting
REG_PIN_TYPE_2                 = 0x7f80046C   #   Pin type setting
REG_I2S_CFG                    = 0x7f800800   #   I2S configuration registers
REG_I2S_CTL                    = 0x7f800804   #   I2S control registers
REG_I2S_STAT                   = 0x7f800810   #   I2S status
REG_I2S_PAD_CFG                = 0x7f800814   #   I2S padding configuration

# Enums

ADPCM_SAMPLES                  = 2
ALPHA                          = 5
ALWAYS                         = 7
ANIM_HOLD                      = 2
ANIM_LOOP                      = 1
ANIM_ONCE                      = 0
ARGB1555                       = 0
ARGB2                          = 5
ARGB4                          = 6
ARGB6                          = 23
ARGB8                          = 20
BARGRAPH                       = 11
BILINEAR                       = 1
BITMAPS                        = 1
BLUE                           = 4
BORDER                         = 0
CMDBUF_SIZE                    = 0x4000
COMPRESSED_RGBA_ASTC_10x10_KHR = 0x93bb
COMPRESSED_RGBA_ASTC_10x5_KHR  = 0x93b8
COMPRESSED_RGBA_ASTC_10x6_KHR  = 0x93b9
COMPRESSED_RGBA_ASTC_10x8_KHR  = 0x93ba
COMPRESSED_RGBA_ASTC_12x10_KHR = 0x93bc
COMPRESSED_RGBA_ASTC_12x12_KHR = 0x93bd
COMPRESSED_RGBA_ASTC_4x4_KHR   = 0x93b0
COMPRESSED_RGBA_ASTC_5x4_KHR   = 0x93b1
COMPRESSED_RGBA_ASTC_5x5_KHR   = 0x93b2
COMPRESSED_RGBA_ASTC_6x5_KHR   = 0x93b3
COMPRESSED_RGBA_ASTC_6x6_KHR   = 0x93b4
COMPRESSED_RGBA_ASTC_8x5_KHR   = 0x93b5
COMPRESSED_RGBA_ASTC_8x6_KHR   = 0x93b6
COMPRESSED_RGBA_ASTC_8x8_KHR   = 0x93b7
CORNER_ZERO                    = 0
CTOUCH_MODE_COMPATIBILITY      = 1
CTOUCH_MODE_EXTENDED           = 0
DECR                           = 4
DLSWAP_DONE                    = 0
DLSWAP_FRAME                   = 2
DST_ALPHA                      = 3
EDGE_STRIP_A                   = 7
EDGE_STRIP_B                   = 8
EDGE_STRIP_L                   = 6
EDGE_STRIP_R                   = 5
EDGE_ZERO                      = 1
EQUAL                          = 5
FLASH_STATUS_BASIC             = 2
FLASH_STATUS_DETACHED          = 1
FLASH_STATUS_FULL              = 3
FLASH_STATUS_INIT              = 0
GEQUAL                         = 4
GLFORMAT                       = 31
GREATER                        = 3
GREEN                          = 3
INCR                           = 3
INT_CMDEMPTY                   = 0x20
INT_CMDFLAG                    = 0x40
INT_CONVCOMPLETE               = 0x80
INT_PLAYBACK                   = 0x10
INT_SOUND                      = 0x08
INT_SWAP                       = 0x01
INT_TAG                        = 0x04
INT_TOUCH                      = 0x02
INVERT                         = 5
KEEP                           = 1
L1                             = 1
L2                             = 17
L4                             = 2
L8                             = 3
LA1                            = 24
LA2                            = 25
LA4                            = 26
LA8                            = 27
LEQUAL                         = 2
LESS                           = 1
LINEAR_SAMPLES                 = 0
LINES                          = 3
LINE_STRIP                     = 4
NEAREST                        = 0
NEVER                          = 0
NOTEQUAL                       = 6
ONE                            = 1
ONE_MINUS_DST_ALPHA            = 5
ONE_MINUS_SRC_ALPHA            = 4
OPT_3D                         = 0
OPT_1BIT                       = 0
OPT_4BIT                       = 2
OPT_BASELINE                   = 0x8000
OPT_CASESENSITIVE              = 2
OPT_CENTER                     = 0x600
OPT_CENTERX                    = 0x200
OPT_CENTERY                    = 0x400
OPT_COMPLETEREG                = 0x1000
OPT_DIRECT                     = 0x800
OPT_DIRSEP_UNIX                = 8
OPT_DIRSEP_WIN                 = 4
OPT_DITHER                     = 0x100
OPT_FILL                       = 0x2000
OPT_FLASH                      = 0x40
OPT_FLAT                       = 0x100
OPT_FORMAT                     = 0x1000
OPT_FS                         = 0x2000
OPT_FULLSCREEN                 = 8
OPT_FULLSPEED                  = 0
OPT_HALFSPEED                  = 4
OPT_IS_MMC                     = 16
OPT_IS_SD                      = 32
OPT_MEDIAFIFO                  = 16
OPT_MONO                       = 1
OPT_NOBACK                     = 0x1000
OPT_NODL                       = 2
OPT_NOHANDS                    = 0xc000
OPT_NOHM                       = 0x4000
OPT_NOKERN                     = 0x4000
OPT_NOPOINTER                  = 0x4000
OPT_NOSECS                     = 0x8000
OPT_NOTICKS                    = 0x2000
OPT_OVERLAY                    = 0x80
OPT_QUARTERSPEED               = 8
OPT_RGB565                     = 0
OPT_RIGHTX                     = 0x800
OPT_SFNLOWER                   = 1
OPT_SIGNED                     = 0x100
OPT_SIMULATION                 = 1
OPT_SOUND                      = 32
OPT_TRUECOLOR                  = 0x200
OPT_YCBCR                      = 0x400
PALETTED                       = 8
PALETTED4444                   = 15
PALETTED565                    = 14
PALETTED8                      = 16
PALETTEDARGB8                  = 21
POINTS                         = 2
RAM_CMD                        = 0x7f000000
RAM_DL                         = 0x7f008000
RAM_G                          = 0
RAM_REPORT                     = 0x7f004800
RECTS                          = 9
RED                            = 2
REG_CMDB_WRITE                 = 0x7f010000
REPEAT                         = 1
REPLACE                        = 2
RGB332                         = 4
RGB565                         = 7
RGB6                           = 22
RGB8                           = 19
S16S_SAMPLES                   = 4
S16_SAMPLES                    = 3
SRC_ALPHA                      = 2
SWAPCHAIN_0                    = 0xffff00ff
SWAPCHAIN_1                    = 0xffff01ff
SWAPCHAIN_2                    = 0xffff02ff
TEXT8X8                        = 9
TEXTVGA                        = 10
TOUCHMODE_CONTINUOUS           = 3
TOUCHMODE_FRAME                = 2
TOUCHMODE_OFF                  = 0
TOUCHMODE_ONESHOT              = 1
TOUCH_100KHZ                   = 0x800
TOUCH_400KHZ                   = 0x000
TOUCH_AR1021                   = 3
TOUCH_FOCALTECH                = 1
TOUCH_GOODIX                   = 2
TOUCH_ILI2511                  = 4
TOUCH_QUICKSIM                 = 0x8000
TOUCH_TSC2007                  = 5
ULAW_SAMPLES                   = 1
YCBCR                          = 28
ZERO                           = 0

# patch-sevenseg
OPT_DECIMAL                    = 0x10   #   Option to draw a decimal point to the immediate right of the 7 segment.
OPT_TIMECOLON                  = 0x20   # Option to draw a time colon to the immediate right of the 7 segment.
OPT_NUMBER                     = 0x0f   # Option of BCD number to show in segments.
OPT_SEGMENTMASK                = 0x2030 # Mask for above options and vc.OPT_FILL

# patch-dialogs
# The amount of alpha to apply to the background box rectangle 
# behind the text of the message. Set to zero to not apply
# any alpha.
OPT_MSGBGALPHA                 = 0x00ff   
# Option to place the message box in the top third of the screen.
# This is useful to allow space to draw feedback buttons below.
OPT_MSGTOP                     = 0x0200   
# Option to place the message box in the bottom third of the screen.
# This is useful to allow space to draw feedback buttons above.
OPT_MSGBOTTOM                  = 0x0400   
# Option to place the message box aligned to the top or bottom edge of the screen.
# This gives maximum space below or above the message.
OPT_MSGEDGE                    = 0x0800   

# patch-keyboard
OPT_EXTEND_EDGE                = 0x1000 # Option to extend edge keys to fill spaces.
OPT_NO_EXTEND_SPACE            = 0x2000 # Option to not expand space character to maximum extent.
OPT_MAP_SPECIAL_KEYS           = 0x4000 # Options to map special key tags and use premade text instead of mapped font character (Ret, Del, Esc, Aa, ?123, Abc)
OPT_INVERT_SPECIAL             = 0x8000 # Option to invert colours of special keys.
OPT_PRESSED                    = 0x00ff # Option to show key with matching tag code in this byte as pressed.
KEY_RETURN                     = 13     # Definition of value of return key.
KEY_DEL                        = 8      # Definition of value of backspace\delete key.
KEY_TAB                        = 9      # Definition of value of tab key.
KEY_ESC                        = 27     # Definition of value of escape key.
KEY_SHIFT                      = 1      # Definition of value of shift key.
KEY_ALPHA                      = 2      # Definition of value of alpha key.
KEY_NUMBER                     = 3      # Definition of value of number key.
KEY_SYMBOLNUM                  = 4      # Definition of value of symbol key.
KEY_SYMBOLS                    = 5      # Definition of value of symbol key.
KEY_CAPS                       = 6      # Definition of value of caps lock key.
KEY_ALT                        = 11     # Definition of value of alt key.
KEY_CTRL                       = 12     # Definition of value of ctrl key.

# patch-plotgraph
OPT_PLOTHORIZONTAL             = 0      # Option to plot graph horizontally, data on Y-axis
OPT_PLOTVERTICAL               = 1      # Option to plot graph vertically, data on X-axis
OPT_PLOTFILTER                 = 2      # Option to remove duplicate points
OPT_PLOTINVERT                 = 4      # Option to invert data
